/**
 * Generates src/contract.ts: the API's request/response types as plain,
 * dependency-free TypeScript, for clients (udhwa-next, udhwa-admin, a future
 * mobile app). The types in src/types.ts are derived from the services, so
 * the TypeScript checker expands them into concrete object types here.
 *
 *   npm run contract
 *
 * When ../udhwa-next and ../udhwa-admin exist next to this app, the file is
 * also copied to src/lib/api-contract.ts in each of them.
 */
import ts from "typescript";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const typesFile = resolve(root, "src/types.ts");
const enumsFile = resolve(root, "src/generated/prisma/enums.ts");
const outFile = resolve(root, "src/contract.ts");

const configPath = resolve(root, "tsconfig.json");
const parsed = ts.parseJsonConfigFileContent(ts.readConfigFile(configPath, ts.sys.readFile).config, ts.sys, root);
const program = ts.createProgram([typesFile], { ...parsed.options, noEmit: true });
const checker = program.getTypeChecker();
const source = program.getSourceFile(typesFile);
if (!source) throw new Error("src/types.ts not found");

// Enum unions from Prisma's generated enums (`export const X = { A: 'A', ... } as const`).
const enumSrc = readFileSync(enumsFile, "utf8");
const enums: string[] = [];
for (const m of enumSrc.matchAll(/export const (\w+) = \{([\s\S]*?)\} as const/g)) {
  const values = [...m[2].matchAll(/:\s*'([^']+)'/g)].map((v) => JSON.stringify(v[1]));
  enums.push(`export type ${m[1]} = ${values.join(" | ")};`);
}

const flags =
  ts.TypeFormatFlags.NoTruncation |
  ts.TypeFormatFlags.InTypeAlias;

const moduleSymbol = checker.getSymbolAtLocation(source);
if (!moduleSymbol) throw new Error("No module symbol for src/types.ts");
const decls: string[] = [];
for (const sym of checker.getExportsOfModule(moduleSymbol).sort((a, b) => a.name.localeCompare(b.name))) {
  const target = sym.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(sym) : sym;
  const type = checker.getDeclaredTypeOfSymbol(target);
  const text = checker.typeToString(type, undefined, flags);
  decls.push(`export type ${sym.name} = ${text};`);
}

const header = `// GENERATED by udhwa-api (npm run contract) — do not edit by hand.
// Request/response types of the Udhwa API. Dates are revived from ISO strings
// into Date objects by the client. Copies live in udhwa-next and udhwa-admin
// as src/lib/api-contract.ts.

export type JsonValue = unknown;

${enums.join("\n")}
`;

const output = `${header}\n${decls.join("\n\n")}\n`;
writeFileSync(outFile, output);
console.log(`wrote src/contract.ts (${decls.length} types, ${enums.length} enums)`);

for (const app of ["udhwa-next", "udhwa-admin"]) {
  const dir = resolve(root, "..", app, "src/lib");
  if (existsSync(dir)) {
    writeFileSync(resolve(dir, "api-contract.ts"), output);
    console.log(`copied to ${app}/src/lib/api-contract.ts`);
  }
}
