// Offline migration generator using Prisma's Wasm schema engine.
// Used only where Prisma's native engine binaries can't be downloaded.
// Usage: node scripts/migrate-diff.mjs (run inside udhwa-api) <name>   (diffs migrations dir -> schema.prisma)
// In normal environments use `npx prisma migrate dev` instead.
import fs from 'node:fs'; import path from 'node:path';
import { SchemaEngine } from '@prisma/schema-engine-wasm';
import { PrismaPg } from '@prisma/adapter-pg';
import { bindMigrationAwareSqlAdapterFactory } from '@prisma/driver-adapter-utils';
import 'dotenv/config';
const schema = fs.readFileSync('prisma/schema.prisma', 'utf8');
const migDir = 'prisma/migrations';
fs.mkdirSync(migDir, { recursive: true });
const dirs = fs.readdirSync(migDir).filter(d => fs.statSync(path.join(migDir, d)).isDirectory()).sort();
const migrations = dirs.map(d => ({ path: d, migrationFile: { path: 'migration.sql', content: { tag: 'ok', value: fs.readFileSync(path.join(migDir, d, 'migration.sql'), 'utf8') } } }));
const pg = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const adapter = bindMigrationAwareSqlAdapterFactory(pg);
const engine = await SchemaEngine.new({ datamodels: [['schema.prisma', schema]] }, (log) => {}, adapter);
const from = migrations.length ? { tag: 'migrations', baseDir: migDir, lockfile: { path: 'migration_lock.toml', content: 'provider = "postgresql"' }, migrationDirectories: migrations, shadowDbInitScript: '' } : { tag: 'empty' };
const res = await engine.diff({ from, to: { tag: 'schemaDatamodel', files: [{ path: 'schema.prisma', content: schema }] }, script: true, shadowDatabaseUrl: null, exitCode: null, filters: { externalTables: [], externalEnums: [] } });
const sql = res.stdout;
if (!sql.trim() || /^-- This is an empty migration/.test(sql.trim())) { console.log('No changes.'); process.exit(0); }
const name = (process.argv[2] || 'migration').replace(/[^a-z0-9_]/gi, '_');
const ts = new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14);
const out = path.join(migDir, `${ts}_${name}`);
fs.mkdirSync(out, { recursive: true });
fs.writeFileSync(path.join(out, 'migration.sql'), sql);
fs.writeFileSync(path.join(migDir, 'migration_lock.toml'), '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n');
console.log('Wrote', out);
process.exit(0);
